### ISSUE TITLE
xtensa-lx6 fails to build

### ISSUE THREAD

**Issue by Rahix** [Rahix/shared-bus#27]
A recent CI run failed on rust nightly for `xtensa-lx6`, due to the recent removal of the `llvm_asm!` macro: https://github.com/Rahix/shared-bus/runs/4870246626?check_suite_focus=true

@pyaillet, you added support for this platform in #22, maybe you know what the upstream situation with xtensa support is?  What would be the correct course of action here?

**Comment by pyaillet** [comment]
Hi !
I just pushed a PR fixing this build, the upstream crate was renamed and updated.
