### ISSUE TITLE
0.1.3 is not compatible with 0.1.2 for `no_std`

### ISSUE THREAD

**Issue by therealprof** [Rahix/shared-bus#3]
0.1.3 contains a breaking change because it requires additional options in crates pulling it in to compile for `no_std` due to the use of `embedded-hal-mock`:

```
    Updating crates.io index
   Compiling embedded-hal-mock v0.4.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv6m-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `embedded-hal-mock`.

To learn more, run the command again with --verbose.
```

**Comment by therealprof** [comment]
Checking around a bit more using `embedded-hal-mock` will not work at all due to this section on https://crates.io/crates/embedded-hal-mock:
```
no_std
Currently this crate is not no_std. If you think this is important, let me know.
```

cc: @ryankurte

**Comment by Rahix** [comment]
Oh, that was unintentional, `embedded-hal-mock` should be a dev-dependency anyway ... I'll fix it asap
