### ISSUE TITLE
What kind of shared bus should I use?

### ISSUE THREAD

**Issue by za-songguo** [Rahix/shared-bus#51]
I have already wrapped my peripherals with `Arc` and `Mutex`, like this:
```
pub struct AppPeripherals<'a> {
    pub sht31: Arc<Mutex<...>>,
    pub max17048: Arc<Mutex<...>>,
}
```
(The peripherals will be shared across multiple threads.)
What kind of shared bus should I use? `BusManagerSimple` or `BusMutex`?

**Comment by Rahix** [comment]
Hi, sorry for the late response.

When every peripheral lives in its own mutex, you still need one additional mutex guarding the bus itself to ensure mutually exclusive access to it.  As it seems you are using the `Mutex` from `std` for your peripherals, the [`BusManagerStd`](https://docs.rs/shared-bus/0.3.0/shared_bus/type.BusManagerStd.html) would be most appropriate.

However, you can also consider going a different route:  You could put all peripherals into a single big mutex and then ensure exclusive access using the [`BusManagerAtomicCheck`](https://docs.rs/shared-bus/0.3.0/shared_bus/type.BusManagerAtomicCheck.html).  This is particularly useful for frameworks like RTIC.  Check the linked documentation for more details.

**Comment by za-songguo** [comment]
Thanks for your reply. It is useful for me.
